### ISSUE TITLE
NoMethodError: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by shortdudey123** [berkshelf/solve#64] opened 2017-01-24 02:43 UTC
i am trying to do `berks update <cookbook_name>` and it is bombing out on ruby solver

```
bundler: failed to load command: berks (/Users/username/chef/.bundle/ruby/2.3.0/bin/berks)
NoMethodError: undefined method `name' for nil:NilClass
  /Users/username/chef/.bundle/ruby/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:82:in `block in resolve'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `each'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `inject'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `resolve'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/solve-3.1.0/lib/solve.rb:64:in `it!'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/resolver.rb:78:in `resolve'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/installer.rb:175:in `install_from_universe'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/installer.rb:39:in `run'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/berksfile.rb:422:in `install'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/berksfile.rb:447:in `update'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:163:in `update'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:52:in `dispatch'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/lib/berkshelf/cli.rb:27:in `execute!'
  /Users/username/chef/.bundle/ruby/2.3.0/gems/berkshelf-5.2.0/bin/berks:5:in `<top (required)>'
  /Users/username/chef/.bundle/ruby/2.3.0/bin/berks:23:in `load'
  /Users/username/chef/.bundle/ruby/2.3.0/bin/berks:23:in `<top (required)>'
```

Bombs out on the 2nd line since `artifact` is `nil`
```
      unsorted_solution = solution.inject({}) do |stringified_soln, artifact|
        stringified_soln[artifact.name] = artifact.version.to_s
        stringified_soln
      end
```

This appears to fix the issue
```diff
-stringified_soln[artifact.name] = artifact.version.to_s
+stringified_soln[artifact.name] = artifact.version.to_s unless artifact.nil?
```

Doing it for another cookbook works, just not the one i am trying to update

**Comment by tpbowden** [comment] 2017-02-01 11:12
I'm also having this problem and can't pinpoint what exactly is causing it - very annoying. Your fix did solve it though, thanks

**Comment by shortdudey123** [comment] 2017-02-01 20:19
I still haven't been able to track down the source it the `nil` either

**Comment by tpbowden** [comment] 2017-02-02 09:15
No it certainly isn't obvious how this stuff works... It's something to do with resolving transitive cookbook dependencies as when I added all dependencies into a single Berksfile rather than across multiple `metadata.rb` files, deleted ~/.berkshelf and my Berksfile.lock and ran berks install again it all worked...

**Comment by tpbowden** [comment] 2017-02-02 19:56
Have you tried using `gem "dep_selector"` in your Gemfile to see if the problem is resolved?

**Comment by shortdudey123** [comment] 2017-02-02 19:57
Currently `dep_selector` is not in my `Gemfile.lock` at all
I can add it, but i thought it was no longer used and the dependency solutions were switched to this gem

**Comment by tpbowden** [comment] 2017-02-02 20:06
You might need to set `solver :gecode, :required` in your Berksfile as well

**Comment by shortdudey123** [comment] 2017-02-02 20:14
*shivers at the thought of compiling `dep-selector-libgecode`*

**Comment by tpbowden** [comment] 2017-02-02 20:18
Agreed it's a pretty heavy library but it solved the issue for me at least, took a good 5 minutes to compile mind you.

**Comment by ofir-petrushka** [comment] 2017-07-28 23:40
This is the same as: 
https://github.com/berkshelf/solve/issues/67

Easy workaround, add in your Gemfile:
`gem 'molinillo', '< 0.6.0'`

**Comment by thommay** [comment] 2017-08-01 14:29
I've pushed solve 3.1.1 that should resolve this.

**Closed by thommay** 2017-08-01 14:29 UTC
